# -*- coding: utf-8 -*-
"""Housing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vI47oOpGZZm2RZ0gaYxS9CW7s3crySfP
"""

from google.colab import files
uploaded = files.upload()

# 2. Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 3. Load and preview the dataset
df = pd.read_csv("Housing.csv")
df.head()

# 4. Preprocess the dataset (convert categorical variables to numerical if needed)
df = pd.get_dummies(df, drop_first=True)  # one-hot encode categorical variables
df.info()

# 5. Select features and target
# Example: Predict 'price' using simple feature 'area'
X_simple = df[['area']]  # Simple Linear Regression
X_multiple = df.drop('price', axis=1)  # Multiple Linear Regression
y = df['price']

# 6. Split into training and testing sets (for both cases)
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_simple, y, test_size=0.2, random_state=42)
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X_multiple, y, test_size=0.2, random_state=42)

# 7. Train the Linear Regression models
model_simple = LinearRegression()
model_simple.fit(X_train_s, y_train_s)

model_multiple = LinearRegression()
model_multiple.fit(X_train_m, y_train_m)

# 8. Evaluate the models
# Simple Regression Evaluation
y_pred_s = model_simple.predict(X_test_s)
print("Simple Linear Regression")
print("MAE:", mean_absolute_error(y_test_s, y_pred_s))
print("MSE:", mean_squared_error(y_test_s, y_pred_s))
print("R² Score:", r2_score(y_test_s, y_pred_s))

# Multiple Regression Evaluation
y_pred_m = model_multiple.predict(X_test_m)
print("\nMultiple Linear Regression")
print("MAE:", mean_absolute_error(y_test_m, y_pred_m))
print("MSE:", mean_squared_error(y_test_m, y_pred_m))
print("R² Score:", r2_score(y_test_m, y_pred_m))

# 9. Plotting the regression line for Simple Linear Regression
plt.scatter(X_test_s, y_test_s, color='blue', label='Actual')
plt.plot(X_test_s, y_pred_s, color='red', linewidth=2, label='Predicted')
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Simple Linear Regression: Area vs Price")
plt.legend()
plt.grid(True)
plt.show()

# 10. Coefficient interpretation
print("Simple Linear Coefficient (area):", model_simple.coef_[0])
print("Intercept:", model_simple.intercept_)

print("\nMultiple Linear Regression Coefficients:")
coeff_df = pd.DataFrame(model_multiple.coef_, X_multiple.columns, columns=["Coefficient"])
print(coeff_df)